#!/usr/bin/env bash
chmod 777 bootstrap/cache -R
chmod 777 storage/* -R
chmod 777 public/documents
chmod 777 public/pics/* -R

echo ""
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo "!!  If you saw any error, please run this script as root.  !!"
echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
echo ""
